addpath(genpath('functions'));

% Define images to process
imageFileNames = {
    'bluebowl/1.jpg',...
    'bluebowl/2.jpg',...
    'bluebowl/3.jpg',...
    'bluebowl/4.jpg',...
    'bluebowl/5.jpg',...
    'bluebowl/6.jpg',...
    'bluebowl/7.jpg',...
    'bluebowl/8.jpg',...
    'bluebowl/9.jpg',...
    'bluebowl/10.jpg',...
    'bluebowl/11.jpg',...
    'bluebowl/12.jpg',...
    'bluebowl/13.jpg',...
    'bluebowl/14.jpg',...
    'bluebowl/15.jpg',...
    'bluebowl/16.jpg',...
    'bluebowl/17.jpg',...
    'bluebowl/18.jpg',...
    'bluebowl/19.jpg',...
    'bluebowl/20.jpg',...
    'bluebowl/21.jpg',...
    'bluebowl/22.jpg',...
    'bluebowl/23.jpg',...
    'bluebowl/24.jpg',...
    'bluebowl/25.jpg',...
    'bluebowl/26.jpg',...
    'bluebowl/27.jpg',...
    'bluebowl/28.jpg',...
    'bluebowl/29.jpg',...
    'bluebowl/30.jpg',...
    'bluebowl/31.jpg',...
    'bluebowl/32.jpg',...
    'bluebowl/33.jpg',...
    'bluebowl/34.jpg',...
    'bluebowl/35.jpg',...
    'bluebowl/36.jpg',...
    'bluebowl/37.jpg',...
    'bluebowl/38.jpg',...
    'bluebowl/39.jpg',...
    'bluebowl/40.jpg',...
    'bluebowl/41.jpg',...
    'bluebowl/42.jpg',...
    'bluebowl/43.jpg',...
    'bluebowl/44.jpg',...
    'bluebowl/45.jpg',...
    'bluebowl/46.jpg',...
    'bluebowl/47.jpg',...
    'bluebowl/48.jpg',...
    'bluebowl/49.jpg',...
    'bluebowl/50.jpg',...
    'bluebowl/51.jpg',...
    'bluebowl/52.jpg',...
    'bluebowl/53.jpg',...
    'bluebowl/54.jpg',...
    'bluebowl/55.jpg',...
    'bluebowl/56.jpg',...
    'bluebowl/57.jpg',...
    'bluebowl/58.jpg',...
    'bluebowl/59.jpg',...
    'bluebowl/60.jpg',...
    'bluebowl/61.jpg',...
    'bluebowl/62.jpg',...
    'bluebowl/63.jpg',...
    'bluebowl/64.jpg',...
    'bluebowl/65.jpg',...
    };
% 
% for k = 1:length(imageFileNames)
%     impath = imageFileNames{k};
%     resize_im = resizeImage(impath, 1024, 768);
%     out_path = sprintf('%s', impath);
%     imwrite(resize_im, out_path);
% end

% Detect checkerboards in images
[imagePoints, boardSize, imagesUsed] = detectCheckerboardPoints(imageFileNames);
imageFileNames = imageFileNames(imagesUsed);

% Generate world coordinates of the corners of the squares
squareSize = 0.866;  % in units of 'in'
worldPoints = generateCheckerboardPoints(boardSize, squareSize);

% Calibrate the camera
[cameraParams, imagesUsed, estimationErrors] = estimateCameraParameters(imagePoints, worldPoints, ...
    'EstimateSkew', false, 'EstimateTangentialDistortion', false, ...
    'NumRadialDistortionCoefficients', 2, 'WorldUnits', 'in', ...
    'InitialIntrinsicMatrix', [], 'InitialRadialDistortion', []);

frames = createFramesArray(imageFileNames, cameraParams, worldPoints);
save('bluebowl_frames.mat', 'frames');

figure; showExtrinsics(cameraParams,'patternCentric');