addpath(genpath('functions'));

% Define images to process
imageFileNames = {'bluecup2/1.jpg',...
    'bluecup2/2.jpg',...
    'bluecup2/3.jpg',...
    'bluecup2/4.jpg',...
    'bluecup2/5.jpg',...
    'bluecup2/6.jpg',...
    'bluecup2/7.jpg',...
    'bluecup2/8.jpg',...
    'bluecup2/9.jpg',...
    'bluecup2/10.jpg',...
    'bluecup2/11.jpg',...
    'bluecup2/12.jpg',...
    'bluecup2/13.jpg',...
    };
% 
% for k = 1:length(imageFileNames)
%     impath = imageFileNames{k};
%     resize_im = resizeImage(impath, 1024, 768);
%     out_path = sprintf('%s', impath);
%     imwrite(resize_im, out_path);
% end

% Detect checkerboards in images
[imagePoints, boardSize, imagesUsed] = detectCheckerboardPoints(imageFileNames);
imageFileNames = imageFileNames(imagesUsed);

% Generate world coordinates of the corners of the squares
squareSize = 0.866;  % in units of 'in'
worldPoints = generateCheckerboardPoints(boardSize, squareSize);

% Calibrate the camera
[cameraParams, imagesUsed, estimationErrors] = estimateCameraParameters(imagePoints, worldPoints, ...
    'EstimateSkew', false, 'EstimateTangentialDistortion', false, ...
    'NumRadialDistortionCoefficients', 2, 'WorldUnits', 'in', ...
    'InitialIntrinsicMatrix', [], 'InitialRadialDistortion', []);

frames = createFramesArray(imageFileNames, cameraParams, worldPoints);
save('bluecup2_frames.mat', 'frames');

figure; showExtrinsics(cameraParams,'patternCentric');