addpath(genpath('functions'));

% Define images to process
imageFileNames = {
    'bluebowl2/1.jpg',...
    'bluebowl2/2.jpg',...
    'bluebowl2/3.jpg',...
    'bluebowl2/4.jpg',...
    'bluebowl2/5.jpg',...
    'bluebowl2/6.jpg',...
    'bluebowl2/7.jpg',...
    'bluebowl2/8.jpg',...
    'bluebowl2/9.jpg',...
    'bluebowl2/10.jpg',...
    'bluebowl2/11.jpg',...
    'bluebowl2/12.jpg',...
    'bluebowl2/13.jpg',...
    'bluebowl2/14.jpg',...
    'bluebowl2/15.jpg',...
    'bluebowl2/16.jpg',...
    'bluebowl2/17.jpg',...
    'bluebowl2/18.jpg',...
    'bluebowl2/19.jpg',...
    'bluebowl2/20.jpg',...
    };
% 
% for k = 1:length(imageFileNames)
%     impath = imageFileNames{k};
%     resize_im = resizeImage(impath, 1024, 768);
%     out_path = sprintf('%s', impath);
%     imwrite(resize_im, out_path);
% end

% Detect checkerboards in images
[imagePoints, boardSize, imagesUsed] = detectCheckerboardPoints(imageFileNames);
imageFileNames = imageFileNames(imagesUsed);

% Generate world coordinates of the corners of the squares
squareSize = 0.866;  % in units of 'in'
worldPoints = generateCheckerboardPoints(boardSize, squareSize);

% Calibrate the camera
[cameraParams, imagesUsed, estimationErrors] = estimateCameraParameters(imagePoints, worldPoints, ...
    'EstimateSkew', false, 'EstimateTangentialDistortion', false, ...
    'NumRadialDistortionCoefficients', 2, 'WorldUnits', 'in', ...
    'InitialIntrinsicMatrix', [], 'InitialRadialDistortion', []);

frames = createFramesArray(imageFileNames, cameraParams, worldPoints);
save('bluebowl2_frames.mat', 'frames');

figure; showExtrinsics(cameraParams,'patternCentric');