addpath(genpath('functions'));

% Define images to process
imageFileNames = {'bluecup/IMG_0067.jpg',...
    'bluecup/IMG_0068.jpg',...
    'bluecup/IMG_0069.jpg',...
    'bluecup/IMG_0070.jpg',...
    'bluecup/IMG_0071.jpg',...
    'bluecup/IMG_0072.jpg',...
    'bluecup/IMG_0073.jpg',...
    'bluecup/IMG_0074.jpg',...
    'bluecup/IMG_0075.jpg',...
    'bluecup/IMG_0076.jpg',...
    'bluecup/IMG_0077.jpg',...
    'bluecup/IMG_0078.jpg',...
    'bluecup/IMG_0079.jpg',...
    'bluecup/IMG_0080.jpg',...
    'bluecup/IMG_0081.jpg',...
    };

% Detect checkerboards in images
[imagePoints, boardSize, imagesUsed] = detectCheckerboardPoints(imageFileNames);
imageFileNames = imageFileNames(imagesUsed);

% Generate world coordinates of the corners of the squares
squareSize = 1;  % in units of 'in'
worldPoints = generateCheckerboardPoints(boardSize, squareSize);

% Calibrate the camera
[cameraParams, imagesUsed, estimationErrors] = estimateCameraParameters(imagePoints, worldPoints, ...
    'EstimateSkew', false, 'EstimateTangentialDistortion', false, ...
    'NumRadialDistortionCoefficients', 2, 'WorldUnits', 'in', ...
    'InitialIntrinsicMatrix', [], 'InitialRadialDistortion', []);

frames = createFramesArray(imageFileNames, cameraParams);
save('bluecup_frames.mat', 'frames');