addpath(genpath('functions'));

% Define images to process
imageFileNames = {
    'macadamia/1.jpg',...
    'macadamia/2.jpg',...
    'macadamia/3.jpg',...
    'macadamia/4.jpg',...
    'macadamia/5.jpg',...
    'macadamia/6.jpg',...
    'macadamia/7.jpg',...
    'macadamia/8.jpg',...
    'macadamia/9.jpg',...
    'macadamia/10.jpg',...
    'macadamia/11.jpg',...
    'macadamia/12.jpg',...
    'macadamia/13.jpg',...
    'macadamia/14.jpg',...
    'macadamia/15.jpg',...
    'macadamia/16.jpg',...
    };
% 
% for k = 1:length(imageFileNames)
%     impath = imageFileNames{k};
%     resize_im = resizeImage(impath, 1024, 768);
%     out_path = sprintf('%s', impath);
%     imwrite(resize_im, out_path);
% end

% Detect checkerboards in images
[imagePoints, boardSize, imagesUsed] = detectCheckerboardPoints(imageFileNames);
imageFileNames = imageFileNames(imagesUsed);

% Generate world coordinates of the corners of the squares
squareSize = 0.866;  % in units of 'in'
worldPoints = generateCheckerboardPoints(boardSize, squareSize);

% Calibrate the camera
[cameraParams, imagesUsed, estimationErrors] = estimateCameraParameters(imagePoints, worldPoints, ...
    'EstimateSkew', false, 'EstimateTangentialDistortion', false, ...
    'NumRadialDistortionCoefficients', 2, 'WorldUnits', 'in', ...
    'InitialIntrinsicMatrix', [], 'InitialRadialDistortion', []);

frames = createFramesArray(imageFileNames, cameraParams, worldPoints);
save('macadamia_frames.mat', 'frames');

figure; showExtrinsics(cameraParams,'patternCentric');