addpath(genpath('functions'));

% Define images to process
imageFileNames = {
    'redcup/1.jpg',...
    'redcup/2.jpg',...
    'redcup/3.jpg',...
    'redcup/4.jpg',...
    'redcup/5.jpg',...
    'redcup/6.jpg',...
    'redcup/7.jpg',...
    'redcup/8.jpg',...
    'redcup/9.jpg',...
    'redcup/10.jpg',...
    'redcup/11.jpg',...
    'redcup/12.jpg',...
    'redcup/13.jpg',...
    'redcup/14.jpg',...
    'redcup/15.jpg',...
    'redcup/16.jpg',...
    'redcup/17.jpg',...
    'redcup/18.jpg',...
    'redcup/19.jpg',...
    'redcup/20.jpg',...
    'redcup/21.jpg',...
    'redcup/22.jpg',...
    'redcup/23.jpg',...
    'redcup/24.jpg',...
    'redcup/25.jpg',...
    'redcup/26.jpg',...
    'redcup/27.jpg',...
    'redcup/28.jpg',...
    'redcup/29.jpg',...
    'redcup/30.jpg',...
    'redcup/31.jpg',...
    'redcup/32.jpg',...
    'redcup/33.jpg',...
    'redcup/34.jpg',...
    'redcup/35.jpg',...
    'redcup/36.jpg',...
    'redcup/37.jpg',...
    'redcup/38.jpg',...
    'redcup/39.jpg',...
    'redcup/40.jpg',...
    'redcup/41.jpg',...
    'redcup/42.jpg',...
    'redcup/43.jpg',...
    'redcup/44.jpg',...
    };
% 
% for k = 1:length(imageFileNames)
%     impath = imageFileNames{k};
%     resize_im = resizeImage(impath, 1024, 768);
%     out_path = sprintf('%s', impath);
%     imwrite(resize_im, out_path);
% end

% Detect checkerboards in images
[imagePoints, boardSize, imagesUsed] = detectCheckerboardPoints(imageFileNames);
imageFileNames = imageFileNames(imagesUsed);

% Generate world coordinates of the corners of the squares
squareSize = 0.866;  % in units of 'in'
worldPoints = generateCheckerboardPoints(boardSize, squareSize);

% Calibrate the camera
[cameraParams, imagesUsed, estimationErrors] = estimateCameraParameters(imagePoints, worldPoints, ...
    'EstimateSkew', false, 'EstimateTangentialDistortion', false, ...
    'NumRadialDistortionCoefficients', 2, 'WorldUnits', 'in', ...
    'InitialIntrinsicMatrix', [], 'InitialRadialDistortion', []);

frames = createFramesArray(imageFileNames, cameraParams, worldPoints);
save('redcup_frames.mat', 'frames');

figure; showExtrinsics(cameraParams,'patternCentric');